card:
  is_feature_enabled: false
  product_name: Card
  time_pass: no re
  again: yes
  scheduler:
    clearing_settlement_scheduler:
      poll:
        interval: "*/5 * * * * *"

compliance:
   tru-narrative:
     poll:
       time: PT10S

rate-limit: '{
  "service_path_rate_limit_config": {
    "app": {
      "is_rate_limit_enabled": false,
      "header_key": "x-device-id",
      "path": [
        "/api/v1/internal/**",
        "/api/v1/dev/**"
      ],
      "bucket_expiration_time_in_minutes": 10,
      "bucket_capacity": 2,
      "refill_tokens_per_minute": 2,
      "initial_token": 2
    }
  }
}'
