name: Trigger Eureka Client Refresh

on:
  push:
    branches:
      - main

jobs:
  trigger_refresh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Specify your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Install ngrok
      uses: wernight/ngrok-action@v1

    - name: Start ngrok tunnel
      run: ngrok http 8080  # Replace 8080 with the actual port
      id: ngrok

    - name: Set ngrok URL
      id: set_ngrok_url
      run: echo "::set-output name=ngrok_url::$(cat ngrok-url.txt)"

    - name: Trigger Eureka Client Refresh
      needs: set_ngrok_url
      run: |
        echo "Ngrok URL: ${{ needs.set_ngrok_url.outputs.ngrok_url }}"
        python3 scripts/trigger_refresh.py ${{ needs.set_ngrok_url.outputs.ngrok_url }}
