name: Trigger Eureka Client Refresh

on:
  push:
    branches:
      - main

jobs:
  trigger_refresh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Specify your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Get ngrok public URL
      id: ngrok
      run: |
        ngrok_url=$(curl -s http://localhost:4040/api/tunnels | jq -r .tunnels[0].public_url)
        echo "Ngrok URL: $ngrok_url"
        echo "::set-output name=url::$ngrok_url"

    - name: Trigger Eureka Client Refresh
      run: |
        echo "Ngrok URL: ${{ steps.ngrok.outputs.url }}"
        python3 scripts/trigger_refresh.py ${{ steps.ngrok.outputs.url }}
