name: Trigger Eureka Client Refresh

on:
  push:
    branches:
      - main

jobs:
  trigger_refresh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Trigger Eureka Client Refresh
      run: |
        python3 scripts/trigger_refresh.py
