name: refresh-config-properties

on:
  workflow_dispatch:
    inputs:
      stack_name:
        required: true
        type: choice
        options:
          - test
          - nonprod
          - prod
      product:
        required: true
        type: choice
        options:
          - hugohub_sg
          - hugosave_sg
          - hugohub_pk
          - hugobank_pk

jobs:
  do-nothing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run a Command
        run: echo "Hi vamshi"
