name: refresh-config-properties

on:
  workflow_call:
    inputs:
      stack_name:
        required: true
        type: string
      product:
        required: true
        type: string

jobs:
  do-nothing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run a Command
        run: echo "Hi vamshi"
