name: refresh-config-properties

on:
  workflow_dispatch:

jobs:
  do-nothing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run a Command
        run: echo "Hi vamshi"
